// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpSqvHeGJg-mVY_UisYO-tzvW-7R0Lsbs',
    appId: '1:839520527744:web:9ec9e4a07dd85806514d65',
    messagingSenderId: '839520527744',
    projectId: 'todoapplication-214fc',
    authDomain: 'todoapplication-214fc.firebaseapp.com',
    storageBucket: 'todoapplication-214fc.appspot.com',
    measurementId: 'G-L1KGVLBVS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxP2gFxjabRtRU1r3bITQkpAWs-4AH2bs',
    appId: '1:839520527744:android:839778329c0e1161514d65',
    messagingSenderId: '839520527744',
    projectId: 'todoapplication-214fc',
    storageBucket: 'todoapplication-214fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurZWyr1sP9w30KTUN59oRU0vFGc83M9E',
    appId: '1:839520527744:ios:5f3038a367a28c9b514d65',
    messagingSenderId: '839520527744',
    projectId: 'todoapplication-214fc',
    storageBucket: 'todoapplication-214fc.appspot.com',
    iosBundleId: 'com.example.notesapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCurZWyr1sP9w30KTUN59oRU0vFGc83M9E',
    appId: '1:839520527744:ios:5f3038a367a28c9b514d65',
    messagingSenderId: '839520527744',
    projectId: 'todoapplication-214fc',
    storageBucket: 'todoapplication-214fc.appspot.com',
    iosBundleId: 'com.example.notesapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpSqvHeGJg-mVY_UisYO-tzvW-7R0Lsbs',
    appId: '1:839520527744:web:10fd271c7f4d7dd4514d65',
    messagingSenderId: '839520527744',
    projectId: 'todoapplication-214fc',
    authDomain: 'todoapplication-214fc.firebaseapp.com',
    storageBucket: 'todoapplication-214fc.appspot.com',
    measurementId: 'G-XKX3GKWCZS',
  );
}
